### ISSUE TITLE
Easy - Android SDK v1.2.1 Library Not Released

### ISSUE THREAD

**Issue by uttampancholi** [Nets-eCom/Nets-Easy-Android-SDK#7]
Easy - Android SDK v1.2.1 Library Not Released on mavenCentral as well jcenter [https://mvnrepository.com/artifact/eu.nets.mia/mia-sdk?repo=jcenter] , there is still an older version of Library which is v1.2.0 and in your all Document you mentioned to use [implementation('eu.nets.mia:mia-sdk:1.2.1') { transitive = true;}] this library , and when we are using this v1.2.1 Library it's showing = > [Could not find eu.nets.mia:mia-sdk:1.2.1.]  library , because its not released. 
so please correct the document.

**Comment by Nets-in-app** [comment]
Hi @uttampancholi  we would recommened you to use our latest sdk of version 1.3.0. Please let us know if you face any issues.

BR

**Comment by Nets-in-app** [comment]
Hi @uttampancholi 

Hope you were able to integrate our latest version. We are closing this issue, please feel free to raise a new issue if you face any difficulties.

BR
